// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNnKLpbfe1_4tM8bOXXCEa-JKo1XNwOE',
    appId: '1:553741439859:web:b1d5adbaaa14e43b92ab06',
    messagingSenderId: '553741439859',
    projectId: 'pizzerie-31a02',
    authDomain: 'pizzerie-31a02.firebaseapp.com',
    storageBucket: 'pizzerie-31a02.firebasestorage.app',
    measurementId: 'G-9Y6Z4W1ETR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC505guNX0n3ouIeqZRXn4w-pXi4rgji8c',
    appId: '1:553741439859:android:544e2a314e0e1f1792ab06',
    messagingSenderId: '553741439859',
    projectId: 'pizzerie-31a02',
    storageBucket: 'pizzerie-31a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFh7oicBYKrWr5KNKYhoPex119zGctrkk',
    appId: '1:553741439859:ios:16292dd724f809ab92ab06',
    messagingSenderId: '553741439859',
    projectId: 'pizzerie-31a02',
    storageBucket: 'pizzerie-31a02.firebasestorage.app',
    iosBundleId: 'com.example.rotante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFh7oicBYKrWr5KNKYhoPex119zGctrkk',
    appId: '1:553741439859:ios:16292dd724f809ab92ab06',
    messagingSenderId: '553741439859',
    projectId: 'pizzerie-31a02',
    storageBucket: 'pizzerie-31a02.firebasestorage.app',
    iosBundleId: 'com.example.rotante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqNnKLpbfe1_4tM8bOXXCEa-JKo1XNwOE',
    appId: '1:553741439859:web:e338d08ef75fec7292ab06',
    messagingSenderId: '553741439859',
    projectId: 'pizzerie-31a02',
    authDomain: 'pizzerie-31a02.firebaseapp.com',
    storageBucket: 'pizzerie-31a02.firebasestorage.app',
    measurementId: 'G-8LSCK22RJY',
  );
}
