import 'dart:io';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import '../../core/utils/logger.dart';

/// Environment configuration for the application.
///
/// Firebase configuration should NOT be in .env file!
/// Firebase uses platform-specific config files:
/// - Android: android/app/google-services.json
/// - iOS: ios/Runner/GoogleService-Info.plist
/// - Web/all: lib/firebase_options.dart (generated by FlutterFire CLI)
///
/// Only Supabase credentials should be in .env for security.
class EnvConfig {
  static const _envFile = '.env';

  /// Check if .env file has been loaded
  static bool get isLoaded => dotenv.isInitialized;

  /// Load .env file (idempotent)
  static Future<void> load() async {
    if (!isLoaded) {
      await dotenv.load(fileName: _envFile);
    }
  }

  static String? _read(String key) {
    final value = dotenv.env[key];
    if (value == null) return null;
    final trimmed = value.trim();
    return trimmed.isEmpty ? null : trimmed;
  }

  /// Supabase project URL
  static String get supabaseUrl => _read('SUPABASE_URL') ?? '';

  /// Supabase anonymous key
  static String get supabaseAnonKey => _read('SUPABASE_ANON_KEY') ?? '';

  /// Google Maps API key (for geocoding and places autocomplete)
  static String get googleMapsApiKey => _read('GOOGLE_MAPS_API_KEY') ?? '';

  /// Stripe publishable key (for card payments)
  static String get stripePublishableKey =>
      _read('STRIPE_PUBLISHABLE_KEY') ?? '';

  /// Check if running on Windows
  static bool get isWindows {
    try {
      return Platform.isWindows;
    } catch (_) {
      return false;
    }
  }

  /// Verify that all required environment variables are configured
  static bool get isValid {
    return supabaseUrl.isNotEmpty && supabaseAnonKey.isNotEmpty;
  }

  /// Print configuration status (for debugging)
  static void printStatus() {
    Logger.info('=== ENV CONFIG STATUS ===', tag: 'EnvConfig');
    Logger.info(
      'Supabase URL: ${supabaseUrl.isNotEmpty ? "✓" : "MISSING"}',
      tag: 'EnvConfig',
    );
    Logger.info(
      'Supabase Key: ${supabaseAnonKey.isNotEmpty ? "✓" : "MISSING"}',
      tag: 'EnvConfig',
    );
    Logger.info('Valid: $isValid', tag: 'EnvConfig');
    Logger.info('========================', tag: 'EnvConfig');
  }
}
